# Generated by Django 4.2.19 on 2025-03-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('booked_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО студента')),
            ],
        ),
    ]
