# Generated by Django 4.2.19 on 2025-03-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], help_text='0 – понедельник, 6 – воскресенье')),
                ('start_time', models.TimeField(help_text='Время начала консультации (в мск)')),
                ('end_time', models.TimeField(help_text='Время окончания консультации (в мск)')),
                ('slot_duration', models.PositiveIntegerField(help_text='Длительность слота в минутах')),
            ],
        ),
    ]
