# Generated by Django 4.2.19 on 2025-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_consultationscheduleconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_day', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], help_text='День недели, когда открывается запись на следующую неделю')),
                ('open_time', models.TimeField(help_text='Время открытия записи в этот день (МСК)')),
            ],
        ),
        migrations.AlterField(
            model_name='consultationscheduleconfig',
            name='end_time',
            field=models.TimeField(help_text='Время окончания консультации (МСК)'),
        ),
        migrations.AlterField(
            model_name='consultationscheduleconfig',
            name='start_time',
            field=models.TimeField(help_text='Время начала консультации (МСК)'),
        ),
    ]
